"""added ticker to asset table

Revision ID: 6a19f58603c4
Revises: d97fd1ace464
Create Date: 2021-10-22 17:41:33.623037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a19f58603c4'
down_revision = 'd97fd1ace464'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('ticker', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'ticker')
    # ### end Alembic commands ###
