"""empty message

Revision ID: 7c0ca09a2959
Revises: 7bde22d5b9fc
Create Date: 2021-10-28 18:06:00.474956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c0ca09a2959'
down_revision = '7bde22d5b9fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watchlist_stocks', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('watchlist_stocks', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('watchlist_stocks', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_constraint('watchlist_stocks_stock_ticker_fkey', 'watchlist_stocks', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('watchlist_stocks_stock_ticker_fkey', 'watchlist_stocks', 'stocks', ['stock_ticker'], ['ticker'])
    op.drop_column('watchlist_stocks', 'updated_at')
    op.drop_column('watchlist_stocks', 'created_at')
    op.drop_column('watchlist_stocks', 'id')
    # ### end Alembic commands ###
