"""empty message

Revision ID: 0acf32a8756d
Revises: 7c0ca09a2959
Create Date: 2021-10-28 18:11:40.492612

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0acf32a8756d'
down_revision = '7c0ca09a2959'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watchlist_stocks')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watchlist_stocks',
    sa.Column('watchlist_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('stock_ticker', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], name='watchlist_stocks_watchlist_id_fkey'),
    sa.PrimaryKeyConstraint('watchlist_id', 'stock_ticker', name='watchlist_stocks_pkey')
    )
    # ### end Alembic commands ###
