"""empty message

Revision ID: 7bde22d5b9fc
Revises: a6b9461b2d2b
Create Date: 2021-10-28 09:45:32.104536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bde22d5b9fc'
down_revision = 'a6b9461b2d2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('cost', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'cost')
    # ### end Alembic commands ###
