"""watchlist removed stock_id

Revision ID: 8fba9f2f30a0
Revises: 6a19f58603c4
Create Date: 2021-10-23 15:47:58.495503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fba9f2f30a0'
down_revision = '6a19f58603c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('watchlists_stock_id_fkey', 'watchlists', type_='foreignkey')
    op.drop_column('watchlists', 'stock_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watchlists', sa.Column('stock_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('watchlists_stock_id_fkey', 'watchlists', 'stocks', ['stock_id'], ['id'])
 
    # ### end Alembic commands ###
