"""ticker fix

Revision ID: 00807cab80b6
Revises: 7a1fb3a5b066
Create Date: 2021-10-21 09:57:56.127540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00807cab80b6'
down_revision = '7a1fb3a5b066'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('assets_ticker_fkey', 'assets', type_='foreignkey')
    op.drop_column('assets', 'ticker')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('ticker', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key('assets_ticker_fkey', 'assets', 'stocks', ['ticker'], ['ticker'])
    # ### end Alembic commands ###
